export const CHANGE_CURRENT_TAB = 'CHANGE_CURRENT_TAB';
export const SELECT_INGREDIENT = 'SELECT_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const CLEAR_ALL_INGREDIENTS = 'CLEAR_ALL_INGREDIENTS';
export const TOGGLE_INF_MODAL = 'TOGGLE_INF_MODAL';
export const OPEN_CART_EMPTY_MODAL = 'OPEN_CART_EMPTY_MODAL';
export const CLOSE_CART_EMPTY_MODAL = ' CLOSE_CART_EMPTY_MODAL';

