export const CHANGE_CURRENT_TAB = 'CHANGE_CURRENT_TAB';
export const SELECT_INGREDIENT = 'SELECT_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const CLEAR_ALL_INGREDIENTS = 'CLEAR_ALL_INGREDIENTS';
export const TOGGLE_INF_MODAL = 'TOGGLE_INF_MODAL';
export const OPEN_MOBILE_CART_MODAL = 'OPEN_MOBILE_CART_MODAL';
export const CLOSE_MOBILE_CART_MODAL = ' CLOSE_MOBILE_CART_MODAL';

